name: Build Requirements

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  req-check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # max-parallel: 6
      matrix:
        os: [ubuntu-latest, windows-2019, macOS-10.15] 
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          # This is just name sake, venv does python job
          python-version: 3.7

      - name: Create and Install package on Ubuntu
        if: runner.os == 'Linux'
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv vEnv ; source vEnv/bin/activate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          cd .. & python
          python -- version
          deactivate ; rm -rf vEnv
      
      - name: Install package on Mac
        if: runner.os == 'macOS'
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv vEnv ; source vEnv/bin/activate
          if ( -f requirements.txt ); then pip install -r requirements.txt; fi
          cd .. & python
          python -- version
          deactivate ; rm -rf vEnv
      
      - name: Install package on Windows
        if: runner.os == 'windows'
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv vEnv ; venv\Scripts\activate.bat
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          cd .. & python
          python -- version
          venv\Scripts\deactivate.bat ; rm -r vEnv

